INSERT INTO gem (name,description,tier) VALUES
	 ('white stone','No power can be felt from it',11)
	,('dim bloodstone','',11)
	,('dirt','',11)
	,('rock','',11)
	,('clay','',11)
	,('bone','',10)
	,('glass','',10)
	,('polished dirt','',10)
	,('ceramic','',10)
	,('porcelain','',9)
	,('plastic','',9)
	,('polished bone','',9)
	,('faint bloodstone','',9)
	,('red stone','',8)
	,('jadeite','',8)
	,('latex','',8)
	,('opalite','',8)
	,('glowing bloodstone','',7)
	,('little blessing','',7)
	,('pyrite','',7)
	,('cat''s eye','',7)
	,('jade','',7)
	,('cubic zirconian','',6)
	,('obsidian','',6)
	,('amber','',6)
	,('garnet','',6)
	,('elixer vitae','',5)
	,('pearl','',5)
	,('blessing','',5)
	,('moonstone','',5)
	,('blinding bloodstone','',5)
	,('aquamarine','',4)
	,('alexandrite','',4)
	,('quick silver','',4)
	,('high blessing','',4)
	,('topaz','',3)
	,('diamond','',3)
	,('ruby','',3)
	,('saphhire','',3)
	,('emerald','',3)
	,('peridot','',3)
	,('nightstone','',2)
	,('amorphous','',2)
	,('glowstone','',2)
	,('crystal','',2)
	,('birthstone','',2)
	,('soulstone','',2)
	,('Kur','',1)
	,('Anki','',1)
	,('Ilnet','',1)
	,('Silvanus','',1)
	,('Rishum','',1)
	,('Ama''at','',0)
	,('Sether','',0)
	,('Selket','',0)
	,('Seker','',0)
	,('Asar','',0)
	,('Aset','',0)
;

INSERT INTO band(name,description,tier) VALUES 
	 ('stone','A band made from a rock',11)
	,('silicate','A cheap material made from sand',10)
	,('plastic','A human made polymer', 9)
	,('silver','A semi-rare mineral found on KISAR',7)
	,('gold','A rare metal sometimes found within KISAR',5)
	,('platinum','A very-rare metal, believed to be created by the gods',2)
	,('mana','A band of pure energy',0)
;


/*
INSERT INTO ring(gem_id,band_id,equip_effect,skill_effect) VALUES
;
*/
